name: EastMesh PUSH Build Check

on:
  push:
    branches: [ develop ]
    paths:
      - "src/**"
      - "examples/**"
      - "variants/**"
      - "platformio.ini"
      - ".github/workflows/eastmesh-push-build-check.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OFFICIAL_MESHCORE_VERSION: ${{ vars.OFFICIAL_MESHCORE_VERSION }}
      PLATFORMIO_BUILD_FLAGS: -UMQTT_DEBUG
    strategy:
      fail-fast: false
      matrix:
        environment:
          - Xiao_S3_WIO_repeater_observer
          - Xiao_S3_WIO_companion_radio_wifi
          - LilyGo_TLora_V2_1_1_6_repeater_observer_no_web
          - LilyGo_TLora_V2_1_1_6_companion_radio_wifi

    steps:
      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build ${{ matrix.environment }}
        run: pio run -e ${{ matrix.environment }}
