name: EastMesh Unified Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OFFICIAL_MESHCORE_VERSION: ${{ vars.OFFICIAL_MESHCORE_VERSION }}
      PLATFORMIO_BUILD_FLAGS: -UMQTT_DEBUG
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Unified Firmwares
        run: |
          /usr/bin/env bash eastmesh-build.sh build-firmware Xiao_S3_WIO_repeater_observer Xiao_S3_WIO_companion_radio_wifi LilyGo_TLora_V2_1_1_6_repeater_observer_no_web LilyGo_TLora_V2_1_1_6_companion_radio_wifi

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: eastmesh-firmwares
          path: out

      - name: Create Unified Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: EastMesh Unified Release ${{ github.ref_name }}
          body: "Unified release containing all 4 firmware builds for version ${{ github.ref_name }}."
          draft: false
          files: out/*
